### PR TITLE
Feature/nd 405 ami lifecycle

### PR DESCRIPTION
**Pull request by AafAnsari**

### CODE REVIEW

**Review by jamesgreen-moj — COMMENTED** [review]
I have concerns with this approach. If we need to roll back to a pre-existing AMI, we will be unable to do so.

**Review by laurentb4 — APPROVED** [review]
LGTM - changes discussed in Dev refinement

**Review by asifamirat00 — APPROVED** [review]
LGTM

**Comment by jamesgreen-moj** [comment]
Closing and reopening to see if this fixes merge blocked issue:
image

**Pull request merged**
